### ISSUE TITLE
Cant connect to denodo using c

### ISSUE THREAD

**Issue by rpshgupta** [aws-samples/aws-glue-samples#93]
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
Exception in thread "main" 
com.amazonaws.glue.jobexecutor.commands.exception.CommandExecutorException:  Running Container Test: 
	at com.amazonaws.glue.jobexecutor.commands.main.MainStartup.main(MainStartup.java:60)

Caused by: com.amazonaws.glue.jobexecutor.commands.exception.CommandExecutorException: java.lang.IllegalArgumentException: No enum constant com.amazonaws.glue.jobexecutor.commands.jdbc.SupportedDriver.VDB
	at com.amazonaws.glue.jobexecutor.commands.jdbc.JdbcCommandArgumentsUtil.getJdbcArguments(JdbcCommandArgumentsUtil.java:102)
	at com.amazonaws.glue.jobexecutor.commands.jdbc.JdbcCommandExecutor.execute(JdbcCommandExecutor.java:57)
	at com.amazonaws.glue.jobexecutor.commands.main.MainStartup.main(MainStartup.java:46)
Caused by: java.lang.IllegalArgumentException: No enum constant com.amazonaws.glue.jobexecutor.commands.jdbc.SupportedDriver.VDB
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.amazonaws.glue.jobexecutor.commands.jdbc.SupportedDriver.valueOf(SupportedDriver.java:9)
	at com.amazonaws.glue.jobexecutor.commands.jdbc.SupportedDriver.getDriverDetails(SupportedDriver.java:47)
	at com.amazonaws.glue.jobexecutor.commands.jdbc.JdbcCommandArgumentsUtil.getSupportedDriverProperties(JdbcCommandArgumentsUtil.java:232)
	at com.amazonaws.glue.jobexecutor.commands.jdbc.JdbcCommandArgumentsUtil.getJdbcArgumentsFromCatalog(JdbcCommandArgumentsUtil.java:159)

	at com.amazonaws.glue.jobexecutor.commands.jdbc.JdbcCommandArgumentsUtil.getJdbcArguments(JdbcCommandArgumentsUtil.java:97)
	... 2 more

**Comment by moomindani** [comment]
We do not have denodo connector as native connector.
It seems you brought denodo's JDBC drover and used it from DynamicFrame.

We are not sure about JDBC driver's specific parameters, but you should be able to pass JDBC parameters.
Alternatively you can also use Spark's native JDBC reader/writer with the JDBC driver.
